---
title: "Untitled"
author: "Bahman Ajdari"
date: "1/15/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
# Data into R
```{r}
passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv') %>%
  drop_na(password)
```

# Libraries
```{r}
library(tidyverse)
library(lubridate)
```

#EDA
```{r}
passwords %>%
  count(time_unit, sort = FALSE)
passwords %>%
  count(password, sort = TRUE)
passwords %>%
  filter(is.na(category))
passwords %>%
  ggplot(aes(value, offline_crack_sec))+
  geom_point()
```
  
# K means
```{r}
has_rownames(passwords) # to ckeck if it has row names

# setting row names
password_clean<- passwords %>%
  mutate(value_scaled = case_when(
    time_unit=="years" ~ duration(value, "years"),
    time_unit=="months"~ duration(value, "months"),
    time_unit=="weeks" ~ duration(value, "weeks"),
    time_unit=="days"  ~ duration(value, "weeks"),
    time_unit=="hours" ~ duration(value, "hours"),
    time_unit=="minutes"~duration(value, "minutes"),
    TRUE ~ duration(value,"seconds")
  )) %>%
  remove_rownames()%>%
  column_to_rownames(var = "password") 

password_clean<- password_clean %>%
  mutate(value_scaled = case_when(
    time_unit=="years" ~ duration(value, "years"),
    time_unit=="months"~ duration(value, "months"),
    time_unit=="weeks" ~ duration(value, "weeks"),
    time_unit=="days"  ~ duration(value, "weeks"),
    time_unit=="hours" ~ duration(value, "hours"),
    time_unit=="minutes"~duration(value, "minutes"),
    TRUE ~ duration(value,"seconds")
  ))%>%
  mutate(value_scaled=as.duration(value_scaled))

has_rownames(password_clean)

password_clean$value_scaled
  ggplot(aes(value_scaled, offline_crack_sec))+
  geom_point()
```

```{r}
password_clean<- passwords %>%
  mutate(value_scaled = case_when(
    time_unit=="years" ~ (value*3.154e+7),
    time_unit=="months"~ (value* 2.628e+6),
    time_unit=="weeks" ~ (value* 604800),
    time_unit=="days"  ~ (value* 86400),
    time_unit=="hours" ~ (value* 3600),
    time_unit=="minutes"~(value* 60),
    TRUE ~ value
  ))%>% 
  select(-c(category, time_unit)) %>%
    remove_rownames()%>%
    column_to_rownames(var = "password") 

k_means<- password_clean %>%
  select(c(offline_crack_sec, value_scaled,strength))%>%
  scale() %>%
  kmeans(centers = 3, iter.max = 10)

plot(password_clean ,
         col = k_means$cluster,
         pch = 20, cex = 3)
    points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
```

```{r}
password_clean %>%
  ggplot(aes(offline_crack_sec, value_scaled))+
  geom_point()+
  geom_jitter()+
  scale_x_log10()+
  scale_y_log10()
```

```{r}
fviz_cluster(k_means, data = password_clean,
palette = c("#2E9FDF", "#00AFBB", "#E7B800", "#FC4E07"),
ellipse.type = "euclid", # Concentration ellipse
star.plot = TRUE, # Add segments from centroids to items
geom="point",
#repel = TRUE, # Avoid labe  l overplotting (slow)
ggtheme = theme_minimal())
```

