---
title: "Happiness"
author: "Bahman Ajdari"
date: "9/3/2019"
output: html_document
theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
#loading libraries

```{r}
library(tidyverse)
theme_set(theme_light())
```


Data
```{r}
library(readr)
X2017 <- read_csv("Downloads/world-happiness-report/2017.csv")
X2016 <- read_csv("Downloads/world-happiness-report/2016.csv")
X2015 <- read_csv("Downloads/world-happiness-report/2015.csv")

```
Data cleaning
```{r}
happiness_2015<- X2015 %>%
  janitor::clean_names()

happiness_2016<- X2016 %>%
  janitor::clean_names()

happiness_2017<- X2017 %>%
  janitor::clean_names()

```

Happy countries by happiness scor

```{r}
happiness_2015 %>%
gather(cat, val, -country, -happiness_score)%>%
  filter(cat=="region")%>%
  group_by(val) %>%
  top_n(16, happiness_score)%>%
  ungroup()%>%
    mutate(country=fct_reorder(country, happiness_score))%>%
  ggplot(aes(country, happiness_score, fill=country))+
  geom_col(show.legend = FALSE)+
  coord_flip()+
  facet_wrap(~val, scales = "free_y")+
  scale_y_continuous()+
  theme_light()+
  labs(
    title = "Happy countries by happiness score",
    subtitle = "contries by region",
    x="",
    y=""
  )
```

Join datasets

```{r}
happiness_2015 %>%
  ggplot(aes(economy_gdp_per_capita, happiness_score))+
  geom_point()+
  geom_smooth()+
  geom_text(aes(label=country), check_overlap = TRUE, hjust=1, vjust=1)
```

```{r}
set.seed(123)
row.number <- sample(1:nrow(happiness_2015), 0.8*nrow(happiness_2015))
train_happiness_2015<- happiness_2015[row.number,]
test_happiness_2015<- happiness_2015[-row.number,]
dim(test_happiness_2015)
dim(train_happiness_2015)
library(glmnet)
model2015<- lm(happiness_score ~  economy_gdp_per_capita + family + health_life_expectancy + freedom +trust_government_corruption+generosity, data = happiness_2015)

model2015_1<- lm(happiness_score ~  economy_gdp_per_capita + family + health_life_expectancy + freedom , data = happiness_2015)
summary(model2015)
summary(model2015_1)
plot(model2015_1)

pred1<- predict(model2015_1, newdata = test_happiness_2015)
test_happiness_2015$pred<- pred1

test_happiness_2015 %>%
  select(happiness_score,
         pred) %>%
  mutate(a= pred%/%happiness_score) %>%
  View()
```

