---
title: "SF Trees"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# Read Data into R
```{r}
sf_trees <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-28/sf_trees.csv')
```

Loading Libraries
```{r}
library(tidyverse)
library(ggfittext)
library(lubridate)
library(cowplot)
```

```{r}
sp_separated<- sf_trees %>%
  mutate(species=trimws(species, which = "both"))%>%
  separate(species, into = c("scientific_name", "common_name"), sep = "\\:: ", 
           remove=FALSE, extra = "merge", fill = "right")

p1<- sp_separated %>%
  drop_na(common_name)%>%
  count(common_name, sort = TRUE) %>%
  head(16)%>%
  mutate(common_name=fct_reorder(common_name, n))%>%
  ggplot(aes(common_name, n, fill=n))+
  geom_col(show.legend = FALSE)+
  geom_bar_text(place = "right")+
  coord_flip()+
  labs(
    title = "Most common tree species in San Francisco",
    x="",
    y=""
  )
p1
```

# Who cares the most of the trees in SF
Private caretakers are dominated in SF
```{r}
p2<- sp_separated %>%
    drop_na(common_name) %>%
    mutate(common_name=fct_lump(common_name,6)) %>%
    mutate(caretaker=fct_lump(caretaker, 6, other_level = "Other Caretakers")) %>%
    ggplot(aes(x=caretaker,fill=common_name))+
    geom_bar(position = "fill")+
    scale_fill_brewer(palette = 2)+
    coord_flip()+
      theme_minimal()+
  labs(
    title = "Caretakers of Trees in San Francisco",
    subtitle = "Who take care of common trees in SF and to what extend?",
    x="",
    y="",
    fill= "Common Species"
  )+
  theme(
    plot.margin = margin(20, 100, 20, 100),
    plot.title = element_text(face = "bold", size = 16),
    legend.position = "bottom"
  )
p2
```

## Calendar heatmap
Number of trees planted in each month through the years in San Francisco
```{r}
p3<- sp_separated %>%
  drop_na(date) %>% 
  mutate(year=year(date),
         month=factor(month(date), labels = month.name)) %>%
  filter(year>1975) %>%
  group_by(year, month) %>%
  summarise(count=n()) %>%
  ggplot(aes(year, month, fill=count))+
  geom_tile(size=0.2, color="white")+
  scale_fill_gradientn(colors=c("#2c7bb6", "#abd9e9", "#fdae61", "#d7191c")) +
  scale_x_discrete(breaks=seq(1975, 2020, 5), limits = seq(1975, 2020, 5)) +
  theme_minimal()+
  theme(
    aspect.ratio = 1/4,
    panel.grid = element_blank(),
    plot.margin=unit(c(1,1,1,1),"cm"),
    plot.title = element_text(face = "bold", size = 16),
    legend.key.width = unit(0.8, "cm"),
    legend.key.height = unit(0.4, "cm"),
    legend.position = "bottom",
    legend.text = element_text(vjust = 0.5, hjust = 0.5),
    legend.title = element_text(vjust = 0.8)
  )+
  labs(
    title = "Trees of San Francisco",
    subtitle = "Number of trees planted in each month through the years in San Francisco",
    x="",
    y="",
    fill="Number of Trees Planted"
  )
p3
```

# SF map of trees

```{r}
#Get the map background from OpenStreetMap

library(ggmap)
osm_sf <- get_map(location = c(left = -122.5501, bottom = 37.6993, right = -122.3367, top = 37.8116), 
                  zoom = 14 , color = "bw")
# Common trees in SF
common_trees<- sp_separated %>%
  drop_na(common_name)%>%
  drop_na(longitude) %>%
  drop_na(latitude) %>%
  count(common_name, sort = TRUE) %>%
  head(6) %>%
  pull(common_name)

df_trees<- sp_separated %>%
  filter(common_name %in% common_trees)

p4<- ggmap(osm_sf)+
  geom_point(data = df_trees, aes(longitude, latitude, color= common_name), size=.6)+
  scale_color_manual(values = c("#63b7af", "#347474", "#35495e", "#ee8572", "#8cba51", "#fbceb5"))+
  theme_void()+
  theme(
    plot.title = element_text(face = "bold", size = 16),
    legend.position = "bottom"
       )+
  guides(
    colour = guide_legend(override.aes = list(size=5))
        )+
  labs(
    title = "Map of Trees in San Francisco",
    subtitle = "Top 6 Common Species",
    color= ""
        )

p4
```

# Printing Plot

```{r}

plot_grid(p4, p3, nrow = 2)

panel <- glue::glue(p3,p4)
p4+p3
panel
```
