---
title: "Hotel Booking"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
# Working Directory
```{r}
setwd("~/Dropbox/Rstats/TidyTuesday/Hotels")
theme<- theme(
  plot.title = element_text(size=12, face = "bold",hjust = 0.5),
  plot.subtitle = element_text(size = 10, face = "italic", hjust = 0.5),
  panel.grid.minor=element_blank()
)
```

# Reading Data into R
```{r}
hotels <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv')

# Writing CSV file
write_csv(hotels, "hotels.csv")


```

```{r}
library(tidyverse)
library(lubridate)
library(countrycode)
library(cowplot)
```

#Working Directory
Loading dataset
```{r}
setwd("/home/bahman/Dropbox/Rstats/TidyTuesday/Hotels")
hotels <- readr::read_csv("hotels.csv")
```

#Pre-Processing
Country names iso3c
```{r}
hotels_iso3c<- hotels %>%
  filter(!country %in% c("TMP", "NULL")) %>%
  mutate(country= ifelse(country=="CN", "CHN", country)) %>%
  mutate(country_name = countrycode(country, c("iso3c"), "country.name"))
```


# EDA 
```{r}
hotels %>%
  count(hotel) %>%
  mutate(name=countrycode(country,  "iso2c", "country.name"))

hotels%>% #To see how many NAs dataset has
  count(is.na(is_canceled))

hotels %>%
  count(arrival_date_year)
hotels %>%
  count(is_repeated_guest)
hotels %>%
  count(country, sort = TRUE)
```

# Cancellation behaviour among top travellers
```{r}
hotel_cancelation<- hotels_iso3c%>%
  mutate(is_canceled= factor(is_canceled, levels = c(0,1), labels = c("Not Canceled", "Canceled"))) %>%
  add_count(country_name, name = "country_total") %>%
  mutate(country_name=fct_lump(country_name, n = 5)) %>%
  mutate(country_name= fct_reorder(country_name, country_total))%>%
  ggplot(aes(country_name))+
  geom_bar(aes(fill=is_canceled),position = "fill")+
  coord_flip()+
  scale_y_continuous(labels = scales::percent_format())+
  scale_fill_manual(values = c("#434e52","#5b8c85"))+

      theme_light()+
  theme+
  labs(
    title = "Who Cancels Hotel Reservation?",
    subtitle = "Percentages of cancellation vs. successful check-ins among top travellers",
    fill= "",
    x="Country of Origin",
    y=""
  )
hotel_cancelation
# second attempt
# countries with at least 1000 observation and have high rate of total cancellation
# both hotel types
 hotel_type<- hotels_iso3c %>%
    group_by(country_name, hotel) %>%
    summarise(
      total=n(),
      cancelation= sum(is_canceled)
    ) %>%
    mutate(total_country=sum(total)) %>%
    mutate(pct_cancelation=cancelation/total_country) %>%
    mutate(pct_total_cancelation= sum(pct_cancelation)) %>%
    filter(total_country>500)%>% 
        ungroup()%>%
    mutate(country_name= fct_reorder(country_name, pct_cancelation, sum))%>%
    ggplot(aes(country_name, pct_cancelation, fill=hotel))+
    geom_col()+
    scale_fill_manual(values = c("#434e52","#5b8c85"))+
    scale_y_continuous(labels=scales::percent_format(), breaks = seq(0,.6, .1))+
    theme_light()+
    theme+
    coord_flip()+
    labs(
      title= "Countries with High Proportional Cancellation",
      subtitle = "Proportion of cancellation for City Hotels and Resort Hotels among\n countries with at least 500 bookings",
      fill="",
      x="Country of Origin",
      y=""
    )
hotel_type
```

# Who is traveling with childeren
Not in final plot
```{r}
  hotels_iso3c %>%
     filter(is_canceled == 0) %>%
  mutate(
    children = case_when(
      children + babies > 0 ~ "children",
      TRUE ~ "none"
      )
    ) %>%
    group_by(country_name,children)%>%
    summarise(
      n=n()
    ) %>%
    filter(sum(n)>5000) %>%
    mutate(pct=n/sum(n)) %>%
    ungroup() %>%
    top_n(16) %>%
    mutate(country=fct_reorder(country_name, pct)) %>%
    ggplot()+
    geom_col(aes(country_name, pct, fill=children))+
    scale_fill_manual(values = c("#434e52","#5b8c85"), breaks= c("none", "children"), labels=c("No Child","Children" )) +
    scale_y_continuous(labels = scales::percent_format())+
    theme_light()+
  theme+
  coord_flip()+
    labs(
      title = "Travel With Children?",
      subtitle = "Proportion of top travellers who travel with/without children",
      x="Country of Origin",
      y="",
      fill=""
    )
```

# Lead Time
```{r}
book_hotels<- hotels_iso3c %>%
  select(country_name, lead_time, hotel) %>%
  group_by(country_name) %>%
  summarise(
  n=n(),
  avg=mean(lead_time)
)  %>%
  arrange(desc(n)) %>%
  filter(n>1000) %>%
  mutate(mm=mean(avg)) %>%
  mutate(country_name=fct_reorder(country_name, avg))%>%
  ggplot(aes(country_name, y=avg))+
  geom_col(aes(fill=avg), show.legend = FALSE)+
  geom_text(aes(country_name, 5, label=round(avg)))+
  geom_hline(yintercept = 98, color="navy", size=1)+
  annotate("text", x=3.5,y=107.5, label="Average= 98 days", size=4, color="navy")+
  coord_flip()+
  scale_y_continuous(breaks = seq(0,140,20))+
  scale_fill_gradient(low = "#434e52", high = "#5b8c85" )+
  theme_light()+
  theme+
  labs(
    title = "How Soon travellers Book Their Hotels?",
    subtitle = "Average number of days that elapsed between the entering date of the booking into \n the PMS and the arrival date for countries with at least 1000 bookings",
    x="",
    y="Days"
  )
book_hotels

box_plot <- hotels_iso3c %>%
  select(country_name, lead_time, hotel, hotel) %>%
  add_count(country_name) %>%
  filter(n>1000) %>%
  mutate(country_name=fct_reorder(country_name, lead_time, mean))%>%
  ggplot(aes(country_name, lead_time))+
  geom_boxplot(outlier.alpha = 0.2, fill="#5b8c85")+
  coord_flip()+
  theme_light()+
  theme+
  labs(
    title = "Average Lead times",
    subtitle = "Box-Plot for number of days between booking and scheduled arrival time \n for countries with more than 1000 bookings",
    x= "Country of Origin",
    y="Days"
  )

box_plot
```

# Booking Trend
```{r}
hotels_new <- hotels %>%
  mutate(total_length_of_stay = stays_in_weekend_nights + stays_in_week_nights) %>% 
  mutate(date = ymd(paste(arrival_date_year,
                                   arrival_date_month,
                                   arrival_date_day_of_month, sep=" ")))
booking_trend <- hotels_new %>%
  mutate(year=year(date),
         month=month(date, label = TRUE, abbr = TRUE)) %>%
  filter(is_canceled==0) %>%
  group_by(year, month) %>%
  summarise(n=n()) %>%
  ggplot(aes(month, n))+
  geom_line(aes(group=as.factor(year), color=as.factor(year)), size=1)+
  geom_point()+
  theme_light()+
  theme(
    aspect.ratio=1/4,
  plot.margin = margin(30, 0, 0, 0)
)+
  labs(
    title = "Trends in Hotel Bookings",
    subtitle = "Number of successful check-ins per year/month",
    color="",
    x="",
    y=""
  )+
  theme
booking_trend
```

#Final_plot
```{r}
plot_grid(plot_grid(hotel_cancelation, hotel_type, ncol = 2, nrow = 1), booking_trend, plot_grid(box_plot, book_hotels), nrow = 3,rel_heights = c(1,1,1))
```
